name: manga_scraper
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+4
  flutter_bloc: ^6.0.6
  get_it: ^5.0.1
  http: ^0.12.2
  connectivity: ^2.0.2
  webview_flutter: ^1.0.7
  screen: ^0.0.5
  photo_view: ^0.11.1
  share: ^2.0.1
  scrollable_positioned_list: ^0.1.10
  hive: ^1.4.4+1
  path_provider: ^1.6.28
  flutter_background_service: ^0.1.4
  rxdart: ^0.27.0
  moor: ^3.2.0
  moor_generator: ^3.4.1
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.0
  dio: ^3.0.10
  flutter_svg: ^0.19.3
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.0.5
  flushbar: ^1.10.4
  web_scraper: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  hive_generator: ^0.8.2
  flutter_launcher_icons: "^0.8.0"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Italic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-MediumItalic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf